from roboid import *

hamster = Hamster()

hamster.leds("WHITE")
hamster.board_forward()
hamster.left_led("OFF")
hamster.board_right()
hamster.leds("WHITE")
hamster.board_forward()
hamster.right_led("OFF")
hamster.board_left()
hamster.leds("WHITE")
hamster.board_forward()
hamster.left_led("OFF")
hamster.board_right()
hamster.leds("WHITE")
hamster.board_forward()
hamster.right_led("OFF")
hamster.board_left()
hamster.leds("WHITE")
hamster.beep()
